version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root

  php:
    depends_on:
      - db
    build: ./php
    restart: always
    volumes:
      - ./web:/var/www/html

  nginx:
    depends_on:
      - php
      - db
    image: nginx:1.13-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html

volumes:
  db_data: